# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

package:
  name: return_foo
  version: 0.0.5

source:
  git: https://github.com/jackos/return-foo.git
  
about:
  summary: Testing Mojo packages
  repository: https://github.com/jackos/return-foo